SELECT 
    "Account_Id" AS Id,
    "Name"       AS Name,
    "Type"       AS Type,
    "Fax",
    "Phone",
    "Website",
    "Industry"              AS Industry,
    "AccountNumber",
    "SICCode__c",
    "AnnualRevenue"         AS AnnualRevenue,
    "NumberOfEmployees"     AS NumberOfEmployees,
    "Ownership",
    "TickerSymbol",
    "Rating",
    "OwnerId",
    "SLAExpirationDate__c",
    "SLASerialNumber__c",
    "BillingStreet",
    "BillingCity",
    "BillingState",
    "BillingPostalCode",
    "BillingCountry"     AS BillingCountry,
    "ShippingStreet",
    "Description",
    "CleanStatus",
    "CustomerPriority",
    "Active__c",
    "NumberOfLocations__c"   AS NumberOfLocations__c,
    "abcd",
    "LastModifiedDate"

FROM {{source('Salesforce','account')}}