version: 2

models:
    - name: salesforce_account
      columns:
        - name: id
          tests:
            - unique
            - not_null

    - name: salesforce_user
      columns:
        - name: id
          tests:
            - unique
            - not_null

    - name: salesforce_opportunity
      columns:
        - name: id
          tests:
            - unique
            - not_null

    - name: salesforce_lead
      columns:
        - name: id
          tests:
            - unique
            - not_null

    - name: salesforce_old_case
      columns:
        - name: id
          tests:
            - unique
            - not_null

    - name: salesforce_campaign
      columns:
        - name: id
          tests:
            - unique
            - not_null

    - name: salesforce_old_contact
      columns:
        - name: id
          tests:
            - unique
            - not_null

    - name: salesforce_case
      columns:
        - name: Case_id
          tests:
            - unique
            - not_null

    - name: salesforce_contact
      columns:
        - name: Contact_Id
          tests:
            - unique
            - not_null

